import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { fromBase64Url, toBase64Url } from "../src/encoding.js";
import type { PasskeyPolicy } from "../src/policy.js";
import { RelyingParty } from "../src/relying-party.js";
import { PasskeyServer } from "../src/server.js";
import { InMemoryChallengeStore, InMemoryCredentialStore } from "../src/stores.js";
import type { StoredCredential } from "../src/types.js";

/**
 * Wire parity with the PHP twin.
 *
 * `particle-academy/fancy-passkeys` (PHP) asserts against **these same JSON
 * files**. That is the entire reason the pair exists: one React surface, either
 * backend. If a shape changes here it must change there in the same session, or
 * the UI silently starts working against only one of them.
 *
 * The fixtures are generated by `scripts/generate-wire-fixtures.ts` from the
 * real `@simplewebauthn/server`; this test re-drives the same fixed inputs and
 * asserts the live output still matches.
 *
 * Comparison is deep equality of **parsed JSON**. Key order is not part of the
 * contract; the presence, absence, and value of every key is.
 */

interface WireInputs {
  relyingParty: { id: string; name: string; origins: string[] };
  user: { handle: string; name: string; displayName: string };
  challenge: string;
  existingCredentials: { id: string; transports: string[] }[];
  policy: Omit<PasskeyPolicy, "challengeTtlSeconds" | "counterPolicy">;
}

const wireDir = resolve(dirname(fileURLToPath(import.meta.url)), "fixtures", "wire");

function fixture<T>(file: string): T {
  return JSON.parse(readFileSync(resolve(wireDir, file), "utf8")) as T;
}

const inputs = fixture<WireInputs>("inputs.json");

/** Strip `undefined`-valued keys the way `JSON.stringify` does on the way out. */
function asWire(payload: unknown): unknown {
  return JSON.parse(JSON.stringify(payload));
}

function seedCredential(credential: { id: string; transports: string[] }): StoredCredential {
  return {
    id: credential.id,
    publicKey: toBase64Url(new Uint8Array([1, 2, 3])),
    userHandle: inputs.user.handle,
    signCount: 0,
    transports: credential.transports,
    aaguid: "00000000-0000-0000-0000-000000000000",
    backedUp: false,
    backupEligible: false,
    uvInitialized: true,
    attestationFormat: "none",
    name: null,
    createdAt: "2026-01-01T00:00:00.000Z",
    lastUsedAt: null,
    clonedAt: null,
  };
}

function fixtureServer(): PasskeyServer {
  const fixedChallenge = fromBase64Url(inputs.challenge);

  return new PasskeyServer({
    relyingParty: new RelyingParty(inputs.relyingParty),
    policy: inputs.policy,
    challenges: new InMemoryChallengeStore(),
    credentials: new InMemoryCredentialStore(inputs.existingCredentials.map(seedCredential)),
    now: () => Date.parse("2026-01-01T00:00:00.000Z"),
    // Fixed bytes for both the challenge and the opaque state handle. Only the
    // challenge reaches the payload, so this is enough to pin the fixture.
    randomBytes: () => fixedChallenge,
    // No `verifier` — the fixtures are the REAL library's output or they prove
    // nothing about what the PHP twin has to match.
  });
}

describe("wire parity", () => {
  it("emits the fixtured registration options", async () => {
    const { publicKey } = await fixtureServer().startRegistration(inputs.user);

    expect(asWire(publicKey)).toEqual(fixture("registration-options.json"));
  });

  it("emits the fixtured authentication options", async () => {
    // Username-first: `allowCredentials` carries both fixture descriptors,
    // which the empty discoverable case could not exercise.
    const { publicKey } = await fixtureServer().startAuthentication({
      userHandle: inputs.user.handle,
    });

    expect(asWire(publicKey)).toEqual(fixture("authentication-options.json"));
  });

  it("round-trips the fixed inputs as canonical base64url", () => {
    // A fixture that does not round-trip encodes something other than it says.
    expect(toBase64Url(fromBase64Url(inputs.challenge))).toBe(inputs.challenge);
    expect(toBase64Url(fromBase64Url(inputs.user.handle))).toBe(inputs.user.handle);
  });

  it("keeps the fields the PHP twin has to synthesise", () => {
    // `web-auth/webauthn-lib` does not emit these; `WireFormat` in the PHP repo
    // adds them specifically to match. Naming them here means removing one on
    // this side fails loudly rather than leaving PHP emitting a phantom key.
    const registration = fixture<Record<string, unknown>>("registration-options.json");

    expect(registration["hints"]).toEqual([]);
    expect(registration["extensions"]).toMatchObject({ credProps: true });
    expect(registration["authenticatorSelection"]).toMatchObject({ requireResidentKey: false });

    const authentication = fixture<Record<string, unknown>>("authentication-options.json");
    expect(authentication).not.toHaveProperty("hints");
    expect(authentication).not.toHaveProperty("extensions");
  });
});
